config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  post 'contact_us', action: :contact_us, controller: 'home'
  get 'projects', action: :index, controller: 'projects'

  defaults format: :json do
    get 'api/v1/projects.json', to: "projects#index"
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/alpha_log.rb
class AlphaLog < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carousel.rb
class Carousel < ApplicationRecord
  has_one_attached :image

  scope :show, -> { where(display: true) }
end

app/models/contact_u.rb
class ContactU < ApplicationRecord
  enum status: [:unread, :read]
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :location
  belongs_to :contract_status
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :project_status
  has_many_attached :images

  scope :ongoing, -> { where("project_status_id = ?", ProjectStatus.ongoing.id) }
  scope :completed, -> { where("project_status_id = ?", ProjectStatus.completed.id) }

  def address
    [street, city, zipcode].compact.join(', ')
  end
end

app/models/project_status.rb
class ProjectStatus < ApplicationRecord
  def self.completed
    self.find_by(name: "Completed")
  end

  def self.ongoing
    self.find_by(name: "Ongoing")
  end
end

app/models/sample_model.rb
class SampleModel < ApplicationRecord
  has_many_attached :images
end

app/models/service.rb
class Service < ApplicationRecord
  has_one_attached :image

  scope :show, -> { where(display: true) }
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  has_one_attached :image

  enum job_role: ["CEO & Founder", "Co Founder"]

  scope :show, -> { where(display: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :init

  def index; end

  def contact_us
    @contact_us.assign_attributes(contact_us_params)
    if verify_recaptcha(model: @contact_us) && @contact_us.save
      flash[:success] = t(".success")
    else
      flash[:danger] = t(".danger")
    end
    redirect_to :root
  end

  private

  def contact_us_params
    params.permit(:name, :email, :subject, :comment)
  end

  def init
    @sliders  = Carousel.show
    @services = Service.show
    @team_members = TeamMember.show
    @contact_us = ContactU.new
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @ongoing = Project.ongoing.order(start_date: :desc)
    @completed = Project.completed.order(start_date: :desc)

    gon.ongoing   = @ongoing || []
    gon.completed = @completed || []
  end
end

app/controllers/sample_models_controller.rb
class SampleModelsController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sample_models_helper.rb
module SampleModelsHelper
end

app/views/home/_about.html.erb
<!-- About Section -->
<div class="w3-center w3-padding-64" id="about">
  <span class="w3-xlarge w3-border-dark-grey w3-padding-16">About</span>
  <p><%= ENV['about_us'] %></p>
</div>

<div class="w3-row-padding my-team">
  <% @team_members.each_with_index do |team_member| %>
    <div class="w3-third w3-margin-bottom team-member">
      <div class="w3-card-4">
        <div style="background-image: url(<%= rails_blob_path(team_member.image , only_path: true) %>)" class="profile-image"></div>
        <div class="w3-container">
          <h3><%= team_member.full_name %></h3>
          <p class="w3-opacity"><%= team_member.job_role %></p>
          <p><%= team_member.description.html_safe %></p>
          <p>
            <a class="text-decoration-none"  href="mailto:<%= team_member.email %>">
              <span><i class="fa fa-envelope"></i></span><%= team_member.email %></p>
            </a>
          <p><a class="w3-button w3-light-grey w3-block" href="tel:<%= team_member.primary_contact_number %>">Call Now</a></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/_contact.html.erb
<div class="w3-container w3-padding-64 w3-theme-l5" id="contact">
  <div class="w3-row w3-card-4">
    <div class="w3-col m6">
      <%= form_for @contact_us, url: contact_us_path, method: :post, html: { autocomplete: false, class: "w3-container w3-padding-16 w3-white" } do |form| %>
        <span class="w3-xlarge w3-border-dark-grey w3-padding-16">Contact Us</span>
        <div class="w3-section">      
          <label>Name</label>
          <%= form.text_field :name, class: "w3-input w3-section w3-border", required: true %>
        </div>
        <div class="w3-section">      
          <label>Email</label>
          <%= form.text_field :email, class: "w3-input w3-section w3-border", required: true  %>
        </div>
        <div class="w3-section">      
          <label>Subject</label>
          <%= form.text_field :subject, class: "w3-input w3-section w3-border", required: true %>
        </div>
        <div class="w3-section">      
          <label>Message</label>
          <%= form.text_field :comment, class: "w3-input w3-section w3-border", required: true %>
        </div>  
        <%= recaptcha_tags %>
        <%= form.submit "Send Message", class: "w3-button w3-right w3-black" %>
      <% end %>
    </div>
    <div class="w3-col m6 w3-right">
      <div class="w3-container w3-padding-16 w3-white" id="contact-map">
      </div>
    </div>
  </div>
</div>


<script src="leaflet/leaflet.js"></script>

<script>
  var map = L.map('contact-map', {scrollWheelZoom: false, zoomControl: false}).setView([6.8058884, 79.9429199], 14);

  L.control.zoom({position:'bottomleft'}).addTo(map);

  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);

  L.marker([6.8058884, 79.9429199]).addTo(map)
      .bindPopup("<div class='map-label'>ALPHA ENGINEERING SERVICE<br>88, 21 Samindu Ln, Piliyandala 10300</div>")
      .openPopup();
</script>

app/views/home/_contacts.html.erb
<!-- Contact Section -->
<div class="w3-container w3-padding-32" id="contact">
  <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Contact</h3>
  <p>Lets get in touch and talk about your next project.</p>
  <form action="/action_page.php" target="_blank">
    <input class="w3-input w3-border" type="text" placeholder="Name" required name="Name">
    <input class="w3-input w3-section w3-border" type="text" placeholder="Email" required name="Email">
    <input class="w3-input w3-section w3-border" type="text" placeholder="Subject" required name="Subject">
    <input class="w3-input w3-section w3-border" type="text" placeholder="Comment" required name="Comment">
    <button class="w3-button w3-black w3-section" type="submit">
      <i class="fa fa-paper-plane"></i> SEND MESSAGE
    </button>
  </form>
</div>
  
<!-- Image of location/map -->
<div class="w3-container">
  <img src="/w3images/map.jpg" class="w3-image" style="width:100%">
</div>

app/views/home/_services.html.erb
<!-- Services Section -->
<div class="w3-center w3-padding-64" id="services">
  <span class="w3-xlarge w3-border-dark-grey w3-padding-16">Services</span>
  <p><%= ENV['services'] %></p>
</div>

<div class="w3-row-padding">
  <% @services.each_with_index do |service| %>
    <div class="w3-col s12 m6 l4 w3-margin-bottom">
      <div class="w3-display-container service-container">
        <div class="w3-display-middle w3-black w3-padding"><%= service.title %></div>
        <div style="background-image: url(<%= rails_blob_path(service.image , only_path: true) %>)" class="service-image"></div>
        <%#= image_tag(service.image, alt: service.title, style: "width:100%") %>
      </div>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="w3-content main-container">
  <%= render "layouts/sliders" %>
  <%= render "about" %>
  <%= render "services" %>
  <%= render "contact" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="w3-black w3-padding-32">
  <div class="w3-row-padding">
    <div class="w3-col w3-quarter">
      <h5>Follow Us</h5>
      <div class="follow-us-links">
        <a class="w3-button w3-large w3-light-grey" href="<%= ENV['facebook_url'] %>" title="Facebook"><i class="fab fa-facebook"></i></a>
        <a class="w3-button w3-large w3-light-grey" href="<%= ENV['youtube_url'] %>" title="YouTube"><i class="fab fa-youtube"></i></a>
        <a class="w3-button w3-large w3-light-grey" href="<%= ENV['instagram_url'] %>" title="Instagram"><i class="fab fa-instagram"></i></a>
        <a class="w3-button w3-large w3-light-grey" href="<%= ENV['tiktok_url'] %>" title="TikTok"><i class="fab fa-tiktok"></i></a>
        <a class="w3-button w3-large w3-light-grey w3-hide-small" href="<%= ENV['linkedin_url'] %>" title="Linkedin"><i class="fab fa-linkedin-in"></i></a>
      </div>
    </div>

    <div class="w3-col w3-quarter footer-company-details text-left company">
      <h5>Company</h5>
      <ul>
        <li><a href="#" class="text-decoration-none">Terms of service</a></li>
        <li><a href="#" class="text-decoration-none">Privacy policy</a></li>
        <li><a href="#" class="text-decoration-none">Projects</a></li>
        <li><a href="#" class="text-decoration-none">Frequently Asked Questions (FAQ)</a></li>
      </ul>
      <%# <div class="company-log"></div> %>
    </div>

    <div class="w3-col w3-quarter text-left company">
      <h5>Working Hours</h5>
      <div class="working-hours">
        <div class="days">
          <ul>
            <li>Monday - Firday</li>
            <li>Saturday</li>
            <li>Sunday</li>     
          </ul>
        </div>
        <div class="time">
          <ul>
            <li>8AM–8PM</li>
            <li>8AM–2PM</li>
            <li>Closed</li>     
          </ul>
        </div>
      </div>
    </div>

    <div class="w3-col w3-quarter text-left company">
      <h5>ALPHA ENGINEERING SERVICE</h5>
      <ul>
        <li><a class="text-decoration-none" href="https://www.google.com/maps/dir//ALPHA%20ENGINEERING%20SERVICE"><i class="fa fa-fw fa-map-marker"></i>88, 21 Samindu Ln, Piliyandala 10300</a></li>
        <li><a class="text-decoration-none" href="tel:+94716862884"><i class="fa fa-fw fa-phone"></i>071 686 2884</a></li>
        <li><a class="text-decoration-none"  href="mailto:alphaengineeringservices@gmail.com"><i class="fa fa-fw fa-envelope"></i>alphaengineeringservices@gmail.com</a></li>
        <li>REG NO : 123456789</li>  
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Navbar (sit on top) -->
<div class="w3-top site-navbar">
  <div class="w3-bar w3-light-grey w3-wide w3-card site-navbar-container">
    <div class="w3-bar-item company-log"></div>
    <a href="/" class="w3-bar-item w3-button company-title" data-turbolinks="false"><b>ALPHA</b> Engineering Services</a>
    <!-- Float links to the right. Hide them on small screens -->
    <div class="w3-right w3-hide-small site-navbar-items">
      <a href="/#about" class="w3-bar-item w3-bottombar w3-hover-border-color" data-turbolinks="false" onclick="pressed(event)">About</a>
      <a href="/#services" class="w3-bar-item w3-bottombar w3-hover-border-color" data-turbolinks="false" onclick="pressed(event)">Services</a>
      <a href="/projects" class="w3-bar-item w3-bottombar w3-hover-border-color" data-turbolinks="false" onclick="pressed(event)">Projects</a>
      <a href="/#contact" class="w3-bar-item w3-bottombar w3-hover-border-color" data-turbolinks="false" onclick="pressed(event)">Contact Us</a>
    </div>
  </div>
</div>

<% flash.each do |type, message| %>
  <% case type %>
  <% when 'danger' %>
    <div class="w3-panel w3-red w3-display-container flash-message">
  <% when 'success' %>
    <div class="w3-panel w3-green w3-display-container flash-message">
  <% else %>
    <div class="w3-panel w3-blue w3-display-container flash-message">
  <% end %>
    <span onclick="this.parentElement.style.display='none'"
    class="w3-button w3-xlarge w3-display-topright">&times;</span>
    <p><%= message %></p>
  </div>
<% end %>

app/views/layouts/_sliders.html.erb
<!-- Sliders -->
<header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
  <% @sliders.each_with_index do |slider, index| %>
    <div class="slider-container w3-animate-left">
      <div style="background-image: url(<%= rails_blob_path(slider.image , only_path: true) %>)" class="slider-image"></div>
      <div class="w3-display-middle w3-margin-top w3-center">
        <h1 class="w3-large w3-text-white"><span class="w3-padding w3-black"><b><%= slider.title %></b></span><span class="w3-padding w3-hide-small w3-text-light-grey"><%= slider.description.html_safe %></span></h1>
      </div>
    </div>
  <% end %>
  <div class="w3-center w3-container w3-section w3-large w3-text-white w3-display-bottommiddle slider-nav" style="width:100%">
    <% @sliders.each_with_index do |slider, index| %>
      <span class="w3-badge demo w3-border w3-transparent w3-hover-white" onclick="currentDiv(<%= index + 1 %>)"></span>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aewa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel = "stylesheet" href = "leaflet/leaflet.css"/>
    <%= Gon::Base.render_data %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/022bdf17ad.js" crossorigin="anonymous"></script>
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v11.0&appId=536447540863741&autoLogAppEvents=1" nonce="8mCTFX88"></script>
</html>

app/views/projects/_status.html.erb
<div class="w3-container w3-theme-l5 status-content">
  <div class="w3-row">
    <div class="w3-col m6">
      <div class="w3-container w3-row w3-center w3-dark-grey w3-padding-16" style="margin-top: 45px;">
        <div class="w3-quarter">
          <span class="w3-xxlarge">14+</span>
          <br>Ongoing
        </div>
        <div class="w3-quarter">
          <span class="w3-xxlarge">55+</span>
          <br>Completed
        </div>
        <div class="w3-quarter">
          <span class="w3-xxlarge">89+</span>
          <br>Happy Clients
        </div>
        <div class="w3-quarter">
          <span class="w3-xxlarge">150+</span>
          <br>Meetings
        </div>
      </div>

      <div class="w3-row w3-center">
        <a href="javascript:void(0)" onclick="openStatus(event, 'ongoing');">
          <div class="w3-padding-16 w3-large w3-col m6 tablink w3-bottombar w3-hover-light-grey w3-padding w3-border-color">Ongoing</div>
        </a>
        <a href="javascript:void(0)" onclick="openStatus(event, 'completed');">
          <div class="w3-padding-16 w3-large w3-col m6 tablink w3-bottombar w3-hover-light-grey w3-padding">Completed</div>
        </a>
      </div>
      <div class="w3-row">
        <div id="ongoing" class="w3-container projects">
          <% @ongoing.each do |ongoing_project| %>
            <div class="w3-card w3-white w3-margin project-card" id="<%= "proj#{ongoing_project.id}" %>" onclick="showMeOnMap(event, <%= ongoing_project.lat.to_s %>, <%= ongoing_project.lng.to_s %>);">
              <div class="w3-container">
                <h3><%= ongoing_project.title %></h3>
                <p><%= ongoing_project.description %></p>
                <p>Start date : <%= ongoing_project.start_date %></p>
                <p><%= ongoing_project.address %></p>
              </div>
            </div>
          <% end %>
        </div>
        <div id="completed" class="w3-container projects" style="display:none">
          <% @completed.each do |completed_project| %>
            <div class="w3-card w3-white w3-margin project-card" id="<%= "proj#{completed_project.id}" %>" onclick="showMeOnMap(event, <%= completed_project.lat.to_s %>, <%= completed_project.lng.to_s %>);">
              <div class="w3-container">
                <h3><%= completed_project.title %></h3>
                <p><%= completed_project.description %></p>
                <p>Start date : <%= completed_project.start_date.to_date %></p>
                <p>Completed date : <%= completed_project.end_date.to_date %></p>
                <p><%= completed_project.address %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="w3-col m6">
      <div style="">
        <div class="w3-white" id="projects-map">
        </div>
      </div>
    </div>
  </div>
</div>

<script src="leaflet/leaflet.js"></script>

<script>
  const initZoomLevel = 11;
  var projectsMap = L.map('projects-map', {scrollWheelZoom: false, zoomControl: false})
                     .setView([6.8058884, 79.9429199], initZoomLevel)
                     
  L.control.zoom({position:'bottomleft'}).addTo(projectsMap);

  L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
      maxZoom: 18,
      id: 'mapbox/streets-v11',
      tileSize: 512,
      zoomOffset: -1,
      accessToken: 'pk.eyJ1Ijoia2F1c2hpa3MiLCJhIjoiY2tqazIwZHN0MGExdjJzczJnZHdra2JweiJ9.DwDqTWB8kTASzJkmx13zOA'
    }
  ).addTo(projectsMap);

  var markerGroup = L.layerGroup().addTo(projectsMap);

  function loadMap(status) {
    locations = getLocations(status);
    markerGroup.clearLayers();

    locations.forEach((data, indx) => {
      let marker = L.marker([data.lat.toString(), data.lng.toString()]).addTo(markerGroup).on('click', function(e) {
          clickZoom(e);
          showMe(e, status);
        }
      );
      // bubble label
      let label = "<div style='text-align:center;'><b>"+data.title+"</b><br>"+address(data)+"</div>";
      marker.bindPopup(label).openPopup();
      projectsMap.setView(marker.getLatLng(), initZoomLevel);
    });
  }

  function clickZoom(e) {
    let zoom = projectsMap.getZoom()
    projectsMap.setView(e.target.getLatLng(), zoom);
  }

  function showMeOnMap(e, lat, lng) {
    let zoom = projectsMap.getZoom();
    var latLng = L.latLng(lat, lng);
    projectsMap.setView(latLng, zoom);
    markerGroup.eachLayer(function (layer) {
      markerLatLng = layer._latlng;
      if(markerLatLng.lat === lat && markerLatLng.lng === lng) {
        e.currentTarget.classList.remove("animate-opacity");
        layer.openPopup();
        e.currentTarget.classList.add("animate-opacity");
      }
    });
  }

  function showMe(e, status) {
    let latLng = e.target.getLatLng();
    locations = getLocations(status);

    locations.forEach(data => {
      if(data.lat === latLng.lat && data.lng === latLng.lng) {
        let card = document.getElementById("proj" + data.id.toString());
        card.classList.remove("animate-opacity");
        card.scrollIntoView({behavior: "smooth", block: "center", inline: "center"});
        card.classList.add("animate-opacity");
      }
    })
  }

  function getLocations(status) {
    return status === "ongoing" ? gon.ongoing : gon.completed;
  }

  function removeAnimation() {
    [...document.getElementsByClassName('project-card')].map(item => item.classList.remove('animate-opacity'));
  }

  function address(project) {
    return [project.street, project.city, project.zipcode].filter(Boolean).join(", ");
  }

  function openStatus(evt, status) {
    var i, x, tablinks;
    x = document.getElementsByClassName("projects");
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablink");
    for (i = 0; i < x.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" w3-border-color", "");
    }
    document.getElementById(status).style.display = "block";
    evt.currentTarget.firstElementChild.className += " w3-border-color";

    removeAnimation();
    loadMap(status);
  }

  loadMap("ongoing");
</script>

app/views/projects/index.html.erb
<div class="w3-content main-container">
  <%= render "statistics" %>
  <%= render "status" %>
</div>

app/views/sample_models/index.html.erb
<!-- Page content -->
<div class="w3-content" style="max-width:1564px">
  
</div>